using System;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.EntityFrameworkCore.Metadata;

#nullable disable

namespace Persistence.Migrations
{
    /// <inheritdoc />
    public partial class ComplaintsDB_Added : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // UNDONE SQL COMMAND - FALSELY GENERATED BY ENTITY FRAMEWORK
            //migrationBuilder.RenameColumn(
            //    name: "DATE_SUBMITTED",
            //    table: "complaints",
            //    newName: "DATE_CREATED");

            // MANUAL SQL FOR THE PREVIOUS COMMAND
            migrationBuilder.Sql(
                "ALTER TABLE complaints RENAME COLUMN DATE_SUBMITTED TO DATE_CREATED;"
            );

            migrationBuilder
                .CreateTable(
                    name: "complaint_privacy",
                    columns: table =>
                        new
                        {
                            ID = table
                                .Column<int>(type: "int", nullable: false)
                                .Annotation(
                                    "MySQL:ValueGenerationStrategy",
                                    MySQLValueGenerationStrategy.IdentityColumn
                                ),
                            NAME = table.Column<string>(type: "longtext", nullable: false)
                        },
                    constraints: table =>
                    {
                        table.PrimaryKey("PK_complaint_privacy", x => x.ID);
                    }
                )
                .Annotation("MySQL:Charset", "utf8mb4");

            migrationBuilder
                .CreateTable(
                    name: "complaint_status",
                    columns: table =>
                        new
                        {
                            ID = table
                                .Column<int>(type: "int", nullable: false)
                                .Annotation(
                                    "MySQL:ValueGenerationStrategy",
                                    MySQLValueGenerationStrategy.IdentityColumn
                                ),
                            NAME = table.Column<string>(type: "longtext", nullable: false)
                        },
                    constraints: table =>
                    {
                        table.PrimaryKey("PK_complaint_status", x => x.ID);
                    }
                )
                .Annotation("MySQL:Charset", "utf8mb4");

            migrationBuilder
                .CreateTable(
                    name: "complaint_voters",
                    columns: table =>
                        new
                        {
                            USER_ID = table.Column<int>(type: "int", nullable: false),
                            COMPLAINT_ID = table.Column<int>(type: "int", nullable: false),
                            IS_HOST = table.Column<bool>(type: "tinyint(1)", nullable: false)
                        },
                    constraints: table =>
                    {
                        table.PrimaryKey(
                            "PK_complaint_voters",
                            x => new { x.USER_ID, x.COMPLAINT_ID }
                        );
                        table.ForeignKey(
                            name: "FK_complaint_voters_AspNetUsers_USER_ID",
                            column: x => x.USER_ID,
                            principalTable: "AspNetUsers",
                            principalColumn: "Id",
                            onDelete: ReferentialAction.Cascade
                        );
                        table.ForeignKey(
                            name: "FK_complaint_voters_complaints_COMPLAINT_ID",
                            column: x => x.COMPLAINT_ID,
                            principalTable: "complaints",
                            principalColumn: "ID",
                            onDelete: ReferentialAction.Cascade
                        );
                    }
                )
                .Annotation("MySQL:Charset", "utf8mb4");

            migrationBuilder
                .CreateTable(
                    name: "complaint_types",
                    columns: table =>
                        new
                        {
                            ID = table
                                .Column<int>(type: "int", nullable: false)
                                .Annotation(
                                    "MySQL:ValueGenerationStrategy",
                                    MySQLValueGenerationStrategy.IdentityColumn
                                ),
                            DEPARTMENT = table.Column<int>(type: "int", nullable: false),
                            NAME_AR = table.Column<string>(type: "longtext", nullable: false),
                            NAME_EN = table.Column<string>(type: "longtext", nullable: false),
                            GRADE = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                            PRIVACY = table.Column<int>(type: "int", nullable: false),
                            CREATED_BY = table.Column<int>(type: "int", nullable: false),
                            DATE_CREATED = table.Column<DateTime>(
                                type: "datetime(6)",
                                nullable: false
                            ),
                            LAST_MODIFIED_BY = table.Column<int>(type: "int", nullable: false),
                            DATE_LAST_MODIFIED = table.Column<DateTime>(
                                type: "datetime(6)",
                                nullable: false
                            ),
                            IS_DELETED = table.Column<bool>(type: "tinyint(1)", nullable: false)
                        },
                    constraints: table =>
                    {
                        table.PrimaryKey("PK_complaint_types", x => x.ID);
                        table.ForeignKey(
                            name: "FK_complaint_types_complaint_privacy_PRIVACY",
                            column: x => x.PRIVACY,
                            principalTable: "complaint_privacy",
                            principalColumn: "ID",
                            onDelete: ReferentialAction.Cascade
                        );
                    }
                )
                .Annotation("MySQL:Charset", "utf8mb4");

            migrationBuilder.CreateIndex(
                name: "IX_complaints_STATUS",
                table: "complaints",
                column: "STATUS",
                unique: true
            );

            migrationBuilder.CreateIndex(
                name: "IX_complaints_TYPE",
                table: "complaints",
                column: "TYPE"
            );

            migrationBuilder.CreateIndex(
                name: "IX_complaint_types_PRIVACY",
                table: "complaint_types",
                column: "PRIVACY"
            );

            migrationBuilder.CreateIndex(
                name: "IX_complaint_voters_COMPLAINT_ID",
                table: "complaint_voters",
                column: "COMPLAINT_ID"
            );

            migrationBuilder.AddForeignKey(
                name: "FK_complaints_complaint_status_STATUS",
                table: "complaints",
                column: "STATUS",
                principalTable: "complaint_status",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade
            );

            migrationBuilder.AddForeignKey(
                name: "FK_complaints_complaint_types_TYPE",
                table: "complaints",
                column: "TYPE",
                principalTable: "complaint_types",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade
            );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_complaints_complaint_status_STATUS",
                table: "complaints"
            );

            migrationBuilder.DropForeignKey(
                name: "FK_complaints_complaint_types_TYPE",
                table: "complaints"
            );

            migrationBuilder.DropTable(name: "complaint_status");

            migrationBuilder.DropTable(name: "complaint_types");

            migrationBuilder.DropTable(name: "complaint_voters");

            migrationBuilder.DropTable(name: "complaint_privacy");

            migrationBuilder.DropIndex(name: "IX_complaints_STATUS", table: "complaints");

            migrationBuilder.DropIndex(name: "IX_complaints_TYPE", table: "complaints");

            migrationBuilder.RenameColumn(
                name: "DATE_CREATED",
                table: "complaints",
                newName: "DATE_SUBMITTED"
            );
        }
    }
}
